### ISSUE TITLE
Hello , I got error (UnicodeDecodeError) while installing

### ISSUE THREAD

**Issue by callmefregy** [s/preprocessor#7]
i also already tried with "pip" or "pip3" command. Still occure with the same error code.

![error](https://cloud.githubusercontent.com/assets/22948067/23495689/b9e165b6-ff4c-11e6-9e6b-b6495fe754ab.png)

**Comment by vinodhinir** [comment]
yeah , I am also facing the same issue. Exact same error. Am using Python 3.6

**Comment by s** [comment]
Hello, because of I don't have Windows development environment I am unable to help out. But PRs are welcome.

**Comment by iamRusty** [comment]
Yeah, I get this as well

**Comment by iamRusty** [comment]
Fixed it in #11

**Comment by callmefregy** [comment]
![image](https://cloud.githubusercontent.com/assets/22948067/26273624/ad2b7e20-3d5d-11e7-82d7-3889bcf8ffd2.png)
Im still getting error

**Comment by iamRusty** [comment]
That's because the pip version is still not updated. My PR is still not accepted. For the meantime, download my repo https://github.com/iamRusty/preprocessor and install it manually.

**Comment by callmefregy** [comment]
thanks. now it works!

**Comment by Insiyaa** [comment]
I installed your repo but it says "module 'preprocessor' has no attribute 'clean'"...
